/* Generated By:JavaCC: Do not edit this line. EvaluateurConstants.java */
package Analyseur;

public interface EvaluateurConstants {

  int EOF = 0;
  int PO = 4;
  int PF = 5;
  int PLUS = 6;
  int MOINS = 7;
  int MUL = 8;
  int DIV = 9;
  int PV = 10;
  int EQUAL = 11;
  int LESS = 12;
  int GT = 13;
  int LEQ = 14;
  int GEQ = 15;
  int DIF = 16;
  int SUM = 17;
  int PROD = 18;
  int MOY = 19;
  int SIN = 20;
  int COS = 21;
  int TAN = 22;
  int LOG = 23;
  int LN = 24;
  int POW = 25;
  int SQRT = 26;
  int ABS = 27;
  int VAR = 28;
  int E = 29;
  int MIN = 30;
  int MAX = 31;
  int EcT = 32;
  int AND = 33;
  int OR = 34;
  int NOT = 35;
  int SI = 36;
  int VRAI = 37;
  int FAUX = 38;
  int NOMBRE = 39;
  int DIGITS = 40;
  int LETTRE = 41;
  int Cellule = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"somme\"",
    "\"produit\"",
    "\"moyenne\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"log\"",
    "\"ln\"",
    "\"puissance\"",
    "\"rac\"",
    "\"abs\"",
    "\"var\"",
    "\"esperance\"",
    "\"min\"",
    "\"max\"",
    "\"ecartType\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"si\"",
    "\"vrai\"",
    "\"faux\"",
    "<NOMBRE>",
    "<DIGITS>",
    "<LETTRE>",
    "<Cellule>",
  };

}
